### ISSUE TITLE
7.0 Update

### ISSUE THREAD

**Issue by Alluneve** [attickdoor/MOActionPlugin#100]
making a note here that 7.0 has launched,
like before I'll work to get a working version to PR in as soon as Dalamud is in a Workable state.

preparatory to 7.0 I've been trying to move as many Self-maintained SIGs to use the ClientStructs instead & This will include the QOL changes I've done during the rest of endwalker.

https://github.com/Aqua-1994/MOActionPlugin/tree/Update/7.0

- re-write the CanUseAction method using the Dalamud exposed ActionManager to simplify business logic, removing the need for some specific Sigs, only leaving ground target queue patch
- Fixed the **long-standing quest instance bug**
- introduced feature: Level sync Actions, skipping over stacks if your player's level is not high enough _a stack of target cure 2, target cure 1 will skip over cure 2 in level synced satasha_
- Fixed a bug with role actions and shared actions (like scholar/summoner res) bleeding between jobs an action stack on "Swiftcast" setup on white mage and Astrologian would conflict.
- Moved the UI mouse over logic to instead rely on STRUCTS, making the only self-maintained sig the ground target queueing patch.

**Comment by Aqua-1994** [comment]
I got 99% of it working!

**Ground target queue patch I've disabled for local testing, that's the only todo**

**Comment by Aqua-1994** [comment]
https://github.com/attickdoor/MOActionPlugin/pull/102

**Comment by Aqua-1994** [comment]
Thank you Cara from the dalamud discord for assistance on finding the new sig for the GtQueuepatch
