### ISSUE TITLE
Mouse location is cast on self instead

### ISSUE THREAD

**Issue by xKiisa** [attickdoor/MOActionPlugin#103]
I'm having the problem that actions that are set to "Mouse Location" will be cast on self instead. Tested this with various actions such as Asylum, Earthly Star, Sacred soil

**Comment by giammod** [comment]
Can confirm.

**Comment by banhbobanhtieu** [comment]
I got that issue too!

**Comment by attickdoor** [comment]
Seems that way. I'm not sure how long it will take to resolve this, but it is on my radar.

**Comment by xKiisa** [comment]
Works as intended now, thanks :)
