### ISSUE TITLE
Medica & Medica II missing in WHM abilities

### ISSUE THREAD

**Issue by FrUct1s** [attickdoor/MOActionPlugin#11]
WHM abilitiy dropdown is missing Medica & Medica II

**Comment by Endracion** [comment]
There's nothing to mouse over for those abilities, they're centered on self, no targeting involved.

**Comment by FrUct1s** [comment]
Ah that's why they are missing - I just wanted to use my Medica button to use a different ability while I MO someone (Rescue/Esuna/Raise) - this of course already works with the integrated abilities like "set ability Cure, MO someone = Rescue" but would have loved to be able to use my Medica button for it

Can understand if that's not what the plugin is supposed to be used for but would have appreciated if those abilities could be added anyway for my purpose haha

**Comment by FrUct1s** [comment]
Not an Issue, it's rather a suggestion so I'll create a new Suggestion post for it.
