### ISSUE TITLE
Update broke plugin?

### ISSUE THREAD

**Issue by Endracion** [attickdoor/MOActionPlugin#13]
Maybe it's the recent update, but it doesn't seem like it's working anymore.

**Comment by sbansal5285** [comment]
It isnt working for me as well, I get plugin error when I try to disable plugin, then I have to restart game and install again for it to work. I have to do this everytime I start playing

**Comment by sbansal5285** [comment]
> It isnt working for me as well, I get plugin error when I try to disable plugin, then I have to restart game and install again for it to work. I have to do this everytime I start playing

Uninstalling xlplugins, deleting all configs in roaming, and reinstalling seems to have fixed this issue

**Comment by firecloud42** [comment]
is there a guide somewhere that's step for step on how to set this thing up? the readme section doesn't clarify anything and I'm just guessing and now I see that it might be broken
