### ISSUE TITLE
DRK - Salted Earth not in Action stack setup list

### ISSUE THREAD

**Issue by UDK450** [attickdoor/MOActionPlugin#17]
I tried looking through the code to determine how Ability lists were populated, but couldn't exactly figure out why Salted Earth is not one of the abilities represented. I often use Salted Earth either as mouseover or on my self. It's ground target by default.

**Comment by johnysandels** [comment]
Ground target abilities are not implemented yet. It is planned to be worked on after the at/after the release of Endwalker

**Comment by attickdoor** [comment]
See API4.
