### ISSUE TITLE
Remove stack option

### ISSUE THREAD

**Issue by Eutherin** [attickdoor/MOActionPlugin#18]
It seems like there's no remove action from stack that I can find. Would be nice.
![image](https://user-images.githubusercontent.com/25861695/128267921-f3bb6be7-acf0-4744-89ef-0564aa575dbb.png)

**Comment by CarolineSelf** [comment]
I think you need to resize your window to see the "Delete ability" button.
![window-size](https://user-images.githubusercontent.com/26314084/128950924-407bd555-a572-484c-83df-863399889b26.png)
