### ISSUE TITLE
AoE spells not in WHM spell list 

### ISSUE THREAD

**Issue by Eutherin** [attickdoor/MOActionPlugin#19]
Things like Medica or Holy would be nice to have on field mouseovers for the use of button condensing

**Comment by johnysandels** [comment]
Button condensing is an accidental feature. If the skills aren't targetable, then they won't be able to be used when hovering over a field target. 
I could see an argument being made for when you either don't have a target or your target is invalid though. If you do an attack with nothing selected, or are targetting/hovering a teammate, using an aoe instead would be cool.

**Comment by attickdoor** [comment]
In the current version, only targeted abilities are valid. In the API4 version, all abilities are available.
