### ISSUE TITLE
Multiple stacks for one ability

### ISSUE THREAD

**Issue by colla-v0ce** [attickdoor/MOActionPlugin#21]
I have a (maybe not so?) niche use case, as a controller player who dabbles in AST. I currently have 8 play macros set up, one for each party member, so my hotbar of play macros looks like this:

![image](https://user-images.githubusercontent.com/21060736/129749670-7ea14bfe-dfff-4070-8c7a-779acdf4f1a5.png)

As far as I can tell, MOAction can't do this, unless I just haven't read carefully enough. Using mouseover actions is pretty difficult with a controller and I often fumble trying to manually target party members, so this feature would be really helpful for me.

**Comment by attickdoor** [comment]
Can't happen, except with modifier keys (useless for controller) on the API4 version. You'll simply have to get good at soft targeting with the dpad.
