### ISSUE TITLE
Spell up and downgrades

### ISSUE THREAD

**Issue by costomojin** [attickdoor/MOActionPlugin#23]
I am currently using several healing macro's that will auto downgrade for level sync to avoid button bloat. I stumbled onto your plugin and I see that you do this for the dps spells, however the healing spells do not do this. Example job (AST) spell Benefic Lv2, and Benefic II Lv26. These spells do not downgrade like spell Malefic IV does all the way to Malefic depending on the level sync. Is this a possible option for the near future? The macro's I have work fine however I would like to eliminate the macro delay especially when healing. Here are 2 examples of my macro's:
Greater than and less than symbols before and after "" comments would not let me use them.
/micon "Benefic"
/macroerror off
/ac "Benefic II" mo
/ac "Benefic" mo
/ac "Benefic II" f
/ac Benefic f
/ac "Benefic II" me
/ac Benefic me

and for  AOE heals for the down grade able level sync

/micon "Helios"
/macroerror off
/ac "Aspected Helios"
/ac "Helios"

If this request is at all possible, it would be greatly appreciated.
Thank You

**Comment by mkaito** [comment]
Benefic II is not an upgrade to Benefic. It's a different spell. The same applies to many such healing spells. There's no easy equivalence between them, unlike most damage spells.
