### ISSUE TITLE
Couple additional mouseover abilities request

### ISSUE THREAD

**Issue by kaedys** [attickdoor/MOActionPlugin#25]
There are a couple sets of abilities I'd like to see a mouseover option for, if possible.  Both of these unavailable in Action Stacks mode, but I'd also like them in the set-and-forget "old configuration" mode if possible.

* [Ninja] Most of the Ninjitsu effects would benefit from being about to be mouseover.  Specifically, Fuma Shuriken, Katon, Raiton, Hyoton, Huton, Suiton, Goka Mekkyaku, and Hyosho Ranryu.  Might be as easy as applying it to Ninjitsu, since it turns into these effects, but it'd also need to apply to the 3 Mudra for use during Ten Chi Jin (since that converts the 3 Mudras into one of the above Ninjitsu casts, depending on the order they are hit in).

* [Samurai] Tenka Goken.  Similar to Fuga and Hissatsu: Guren, cone attacks almost mandate having a mouseover set, since they cannot be cast without a target selected and within the target area.  Kaeshi: Goken as well, for the same reason.

**Comment by attickdoor** [comment]
These work exactly as expected on API4. You should be using Ninjutsu and Iaijutsu as your base actions.

**Comment by kaedys** [comment]
Maybe I'm not looking in the correct place, but neither Ninjitsu or Iaijutsu appear in the Base Ability dropdown for their respective classes.  What am I missing?

**Comment by attickdoor** [comment]
You're not on API4.

**Comment by kaedys** [comment]
How do I get on API4, then?  Your README makes no mention of it.  I'm on the testing branch setting in Dalamud.
