### ISSUE TITLE
Add instant ground placement

### ISSUE THREAD

**Issue by attickdoor** [attickdoor/MOActionPlugin#3]
Whether it be at self, target, mouseover, or current mouse location, I'm not sure. This may also be better suited as a separate plugin.

**Comment by Kanarisky** [comment]
Yes please!!! Putting it at current mouse location without having to LMB would be a blessing. Or even having it show you the AoE while you hold the skill's button, then place it when you let go, like League of Legends / Dota 2 smartcast <3
