### ISSUE TITLE
Request for the “enable all” button

### ISSUE THREAD

**Issue by AmenneHolelane** [attickdoor/MOActionPlugin#4]
Would it be possible to split that into 2 different buttons, one for damage abilities and one for everything else? I like using support as MO but damage abilities get finicky and frequently just result in me having to move the mouse off a party member.

**Comment by attickdoor** [comment]
It's doable. I have a bit of a backlog, and the big update I have planned for this plugin would remove the need for that entirely. So it might happen, or I might get off my butt and do the big update instead.
