### ISSUE TITLE
Update for Endwalker

### ISSUE THREAD

**Issue by VieLassiel** [attickdoor/MOActionPlugin#53]
Can we please get this updated for Endwalker?

I know a lot of people complained and didn't show much love but this plugin is great!

Please update it. Q.Q

**Comment by 720mmHowizter** [comment]
Attick said he will probably update it after the savage race, on the meantime try this:
https://github.com/UnknownX7/ReAction
It's already far better than MO in my opinion and the creator is implementing suggestions like crazy

**Comment by VieLassiel** [comment]
Thank you @720mmHowizter for the suggestion.

Also thank you @attickdoor for the update! :)
