### ISSUE TITLE
6.5 update will be out next week

### ISSUE THREAD

**Issue by attickdoor** [attickdoor/MOActionPlugin#90]
i'm out of town this weekend and people get noisier about xivcombo. happy oktoberfest and etc.

**Comment by Krojack** [comment]
Thanks for this update. This is what I like. A notice that the plugin isn't dead and will be updated but IRL is in the way. Other plugins leave you in the dark not knowing if the owner will update or moved on letting it silently die without a message.

Take your time and enjoy what you're doing. =)

**Comment by Aqua-1994** [comment]
Hope my draft helped along.

https://github.com/attickdoor/MOActionPlugin/pull/89

- [v] Adapt to Api9
- [v] Transform direct access to instead use services
- [v] Adapt some direct access sigs to instead use the TargetManager module
- [ ] Ground target Queue patch _this got re-written by SE, different methods and stuff now_

**Comment by attickdoor** [comment]
> Ground target Queue patch this got re-written by SE, different methods and stuff now

unfortunately this is the bit i'm stuck on as well. what a drag.

**Comment by attickdoor** [comment]
i could change to the redirect way and start manually checking a bunch of factors, but i don't like how that feels. do you have any insight to what actually changed?

**Comment by Aqua-1994** [comment]
not really, I'm not that much of a wizard with how the memory and the SE internals work. I'm mostly going with and off the Dalamud API.
albeit it's a skill I'm rather interested in picking up.

from what I was told in the dalamud discord, it's mostly that a couple of methods regarding this were absorbed into one method.

**Comment by TheTylerG** [comment]
> one thing that could be done as a temporary measure

For sure. The ground targeting is nice, but it's not the core reason I use this. The in-game macros are just so clunky and bad. ;_;

**Comment by 542673** [comment]
> For sure. The ground targeting is nice, but it's not the core reason I use this. The in-game macros are just so clunky and bad. 

I also mainly use this plugin just for the mouseover side and not the ground target abilities, i use ReAction instead which has been updated and maybe could help you understand what has been updated in that regard.
I think a lot of people would be happy with a quick update even if ground target queue doesnt work yet :')

**Comment by Aqua-1994** [comment]
> i use ReAction instead which has been updated 

I'd recommend not using third-party plugins in general, as they don't comply with the guidelines set in Dalamud.

**Comment by Aqua-1994** [comment]
I might have a fix (tested locally myself and it seems to have fixed the issue) in 
https://github.com/attickdoor/MOActionPlugin/pull/89 
but i would love to have some extra validation/testing done before speaking with 100% certainty

**Comment by Aqua-1994** [comment]
Issue can be closed

**Comment by attickdoor** [comment]
👍

**Comment by iUngaBunga** [comment]
IS this going to be updated anytime soon?

**Comment by Galborion6** [comment]
Thank you VERY MUCH for fixing Ability Ants! You are great! 👍
